#!/bin/sh

arch=`uname -i`

cd /tmp/ && wget "https://mirrors.dotsrc.org/blender/blender-release/Blender2.79/blender-2.79b-linux-glibc219-$arch.tar.bz2"
echo "Extracting blender-2.79b-linux-glibc219-$arch.tar" && tar -xf "blender-2.79b-linux-glibc219-$arch.tar.bz2" && rm "blender-2.79b-linux-glibc219-$arch.tar.bz2"  && echo "Done!"
cd "/tmp/blender-2.79b-linux-glibc219-$arch/2.79/python/lib/python3.5/" && wget -O "https://github.com/An0n3m0us/DiscordRPBlender/raw/master/discoIPC.zip"
unzip discoIPC.zip && rm discoIPC.zip
cd "/tmp/blender-2.79b-linux-glibc219-$arch/" && wget "https://raw.githubusercontent.com/An0n3m0us/DiscordRPBlender/master/discordrpblender.py"
mv discordrpblender.py discordrpblender.txt && ls

echo
echo "Please input your client ID (18 digits)"
read client_ID

while [ $(echo ${#client_ID}) -ne 18 ]
do
    echo "Client ID is must be 18 digits"
    read client_ID
done
sed -e "s/\${clientID}/$client_ID/" discordrpblender.txt > discordrpblender.py
rm discordrpblender.txt
