#!/bin/sh

cd /tmp/ && wget "https://mirrors.dotsrc.org/blender/blender-release/Blender2.79/blender-2.79b-linux-glibc219-x86_64.tar.bz2"
echo "Extracting blender-2.79b-linux-glibc219-x86_64.tar.bz2" && tar -xf "blender-2.79b-linux-glibc219-x86_64.tar.bz2" && rm "blender-2.79b-linux-glibc219-x86_64.tar.bz2"  && echo "Done!"
cd "/tmp/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/" && wget "https://github.com/An0n3m0us/DiscordRPBlender/raw/master/discoIPC.zip"
unzip discoIPC.zip && rm discoIPC.zip
cd "/tmp/blender-2.79b-linux-glibc219-x86_64/" && wget "https://raw.githubusercontent.com/An0n3m0us/DiscordRPBlender/master/discordrpblender.py"
mv discordrpblender.py discordrpblender.txt && ls
